ace_framework:
  aspirational_layer:
    dependencies: []
  global_strategy_layer:
    dependencies:
      - aspirational_layer
  agent_model_layer:
    dependencies:
      - global_strategy_layer
  executive_function_layer:
    dependencies:
      - agent_model_layer
  cognitive_control_layer:
    dependencies:
      - executive_function_layer
  task_prosecution_layer:
    dependencies:
      - cognitive_control_layer
  interlayer_communication_buses:
    dependencies:
      - aspirational_layer
      - global_strategy_layer
      - agent_model_layer
      - executive_function_layer
      - cognitive_control_layer
      - task_prosecution_layer
  security:
    dependencies:
      - interlayer_communication_buses
